### ISSUE TITLE
deserialise() method bug

### ISSUE THREAD

**Issue by fagiodarkie** [Dugy/serialisable#2]
The `deserialise()` method doesn't work as intended. The parameter passed to `parseJSON` was meant to be `sourceStream` but instead `stream` is passed, resulting in the wrong overload being called. Also, the `preferencesSaving_` flag is set to `true` instead of `false`.

Suggested body:

```
        inline void deserialise(const std::string& source) {
		std::stringstream sourceStream(source);
		std::shared_ptr<JSON> target = parseJSON(sourceStream);
		preferencesJson_ = target;
		if (preferencesJson_->type() == JSONtype::NIL) {
			preferencesJson_ = nullptr;
			return;
		}
		preferencesSaving_ = false;
		serialisation();
		preferencesJson_ = nullptr;
	}
```

**Comment by Dugy** [comment]
Seems I haven't tested this. I have accepted your pull request, so I am closing this now. Thanks.
